### ISSUE TITLE
Latest update conflicting with custom scripts

### ISSUE THREAD

**Issue by TowelSniffer** [hgiesel/anki_script_manager#12]
The latest update seems to have broken anki persistence and my other custom scripts I have. I get this error launching Anki

```
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-10-24 14:17:29

Caught exception:
Traceback (most recent call last):
  File "aqt\main.py", line 286, in onOpenProfile
  File "aqt\main.py", line 427, in loadProfile
  File "aqt\gui_hooks.py", line 2027, in __call__
  File "C:\Users\fionn\AppData\Roaming\Anki2\addons21\1051511270\script.py", line 67, in install_script
    my_meta_script = ami.make_meta_script(
AttributeError: module '656021484.src.lib.registrar.interface' has no attribute 'make_meta_script'
```

and when trying to edit the assets in my note types I get this error
```
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-10-24 14:17:29

Caught exception:
Traceback (most recent call last):
  File "C:\Users\fionn\AppData\Roaming\Anki2\addons21\656021484\src\models.py", line 30, in <lambda>
    lambda: on_assets(models),
  File "C:\Users\fionn\AppData\Roaming\Anki2\addons21\656021484\src\models.py", line 18, in on_assets
    dialog.setupUi(
  File "C:\Users\fionn\AppData\Roaming\Anki2\addons21\656021484\gui_config\config.py", line 47, in setupUi
    self.ui.configWidget.setupUi(self.modelId, scriptSetting)
  File "C:\Users\fionn\AppData\Roaming\Anki2\addons21\656021484\gui_config\script_tab.py", line 65, in setupUi
    self.drawScripts()
  File "C:\Users\fionn\AppData\Roaming\Anki2\addons21\656021484\gui_config\script_tab.py", line 79, in drawScripts
    else get_from_meta(script)
  File "C:\Users\fionn\AppData\Roaming\Anki2\addons21\656021484\gui_config\script_tab.py", line 35, in get_from_meta
    script = iface.getter(meta_script.id, meta_script.storage)
  File "C:\Users\fionn\AppData\Roaming\Anki2\addons21\1051511270\script.py", line 44, in <lambda>
    getter = lambda id, storage: ami.make_script(
AttributeError: module '656021484.src.lib.registrar.interface' has no attribute 'make_script'
```

**Comment by hgiesel** [comment]
I'm sorry to hear this!
I did some refactoring there, which seems to cause this weird issue.

Another solution is to adapt the injections scripts, to use `lib` directly instead of `amr`, and `ami`, like I did here:

https://github.com/hgiesel/closet/blob/8e231ea73e27b2a626f89c0d5bdea7ed1db05cd6/anki/src/hook.py#L21

**Comment by hgiesel** [comment]
Ok, so for some reason `__import__(am).src.lib.interface` imported `src.lib.registrar.interface` instead. No idea why this happens, almost seems like a bug with Python.

I did the easiest fix possible: I renamed `src/lib/registrar/interface.py` to `iface.py`, now it works. I already uploaded the fixed version.

However the tip with `lib` from the previous answer still counts, if you ever want to touch your code  again, you can refactor it to using just `lib`.

**Comment by TowelSniffer** [comment]
Awesome! That was quick, thank you.
