### ISSUE TITLE
Error on applying condition for back or front side

### ISSUE THREAD

**Issue by gleisonkz** [hgiesel/anki_script_manager#24]
I'm trying to inject a script just on front / back side, but I'm getting this error

What did I do wrong?

![image](https://user-images.githubusercontent.com/48810597/113494929-9c7e7980-94c3-11eb-950a-27238878bccd.png)

`An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-04-02 22:07:14

Caught exception:
Traceback (most recent call last):
  File "C:\Users\gleis\AppData\Roaming\Anki2\addons21\656021484\src\gui_config\custom\config.py", line 42, in wbCurrentSetting
    setup_model(self.modelId)
  File "C:\Users\gleis\AppData\Roaming\Anki2\addons21\656021484\src\lib\model_editor.py", line 30, in setup_model
    stringify_setting_for_template(
  File "C:\Users\gleis\AppData\Roaming\Anki2\addons21\656021484\src\lib\stringify.py", line 314, in stringify_setting_for_template
    stringified_scripts = stringify_setting(setting, model_name, cardtype_name, fmt)
  File "C:\Users\gleis\AppData\Roaming\Anki2\addons21\656021484\src\lib\stringify.py", line 263, in stringify_setting
    needs_inject, conditions_simplified = the_parser(script_gotten.conditions)
TypeError: cannot unpack non-iterable NoneType object
`

**Comment by hgiesel** [comment]
Hard to say. It's probably not you, it's the add-on. Is there a reason you need to stay on 2.1.26?
