### ISSUE TITLE
TypeError on "Write to Templates" | Anki 2.1.45 beta 4+

### ISSUE THREAD

**Issue by kleinerpirat** [hgiesel/anki_script_manager#29]
```
Anki 2.1.45 (dev) Python 3.8.10 Qt 5.15.2 PyQt 5.15.2
Platform: Linux
Flags: frz=False ao=True sv=2
Add-ons, last update check: 2021-06-29 13:19:44
Add-ons possibly involved: ⁨Asset Manager⁩

Caught exception:
Traceback (most recent call last):
  File "/home/kleinerpirat/.local/share/Anki2/addons21/656021484/gui_config/config.py", line 58, in writeBackCurrentSetting
    self.write_back_callback(*self.export_data())
  File "/home/kleinerpirat/.local/share/Anki2/addons21/656021484/src/models.py", line 22, in write_back
    setup_model(model_id, html_data, script_data)
  File "/home/kleinerpirat/.local/share/Anki2/addons21/656021484/src/model_editor/__init__.py", line 9, in setup_model
    setup_full(model_id, html, scripts)
  File "/home/kleinerpirat/.local/share/Anki2/addons21/656021484/src/model_editor/setup_html.py", line 208, in setup_full
    insert(unminifieds, template_fmts, lambda: mw.col.models.save(model, True))
  File "/home/kleinerpirat/.local/share/Anki2/addons21/656021484/src/model_editor/minify.py", line 22, in insert_unminified
    process_minifieds(unminifieds, template_fmts, callback)
  File "/home/kleinerpirat/.local/share/Anki2/addons21/656021484/src/model_editor/minifier.py", line 37, in process_minifieds
    callback()
  File "/home/kleinerpirat/.local/share/Anki2/addons21/656021484/src/model_editor/setup_html.py", line 208, in <lambda>
    insert(unminifieds, template_fmts, lambda: mw.col.models.save(model, True))
TypeError: save() takes from 1 to 2 positional arguments but 3 were given
```

Had this exception yesterday when running from upstream, should have been introduced with beta 4 today.

**Comment by hgiesel** [comment]
Thanks for the heads-up! I should keep a list with all broken add-ons...
