### ISSUE TITLE
Error installing custom scipts

### ISSUE THREAD

**Issue by TowelSniffer** [hgiesel/anki_script_manager#6]
I'm getting an error trying to plug my own scripts as. Even just pasting the example template into the addons folder gives this message: 

```
Debug info:
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-09-17 12:55:48

Caught exception:
Traceback (most recent call last):
  File "aqt\main.py", line 286, in onOpenProfile
  File "aqt\main.py", line 427, in loadProfile
  File "aqt\gui_hooks.py", line 1984, in __call__
  File "anki\hooks.py", line 583, in runHook
  File "C:\Users\fionn\AppData\Roaming\Anki2\addons21\example\__init__.py", line 102, in install_script
    amr.register_meta_script(
  File "C:\Users\fionn\AppData\Roaming\Anki2\addons21\656021484\src\lib\registrar.py", line 79, in register_meta_script
    mid = int(model_id)
ValueError: invalid literal for int() with base 10: 'Basic'
```

**Comment by TowelSniffer** [comment]
An update here, I got the idea to use the Anki persistence addon as a template and that works fine, so It's just the example that needs updating by the looks of it.

**Comment by hgiesel** [comment]
Ok, great, but I'll still try to fix it soon. As far I remember that was a v2.1.26 issue

**Comment by hgiesel** [comment]
I just updated it in e61e778096672c8c3a496b1551b73586fdecf6e7, should work fine now.

**Comment by TowelSniffer** [comment]
yeah no issues
